### ISSUE TITLE
Error: sendMessage: Keystore not found

### ISSUE THREAD

**Issue by shravanandoria** [tonlabs/ever-sdk-js#535]
this problem comes while trying to call mint function in the smart contract & this error gets thrown

  const mint_nft = async (provider) => {
    const json = {
      type: "Basic NFT",
      name: "Sample Name",
      description: "Hello world!",
      preview: {
        source:
          "https://venom.network/static/media/bg-main.6b6f0965e7c3b3d9833b.jpg",
        mimetype: "image/png",
      },
      files: [
        {
          source:
            "https://venom.network/static/media/bg-main.6b6f0965e7c3b3d9833b.jpg",
          mimetype: "image/jpg",
        },
      ],
      external_url: "https://venom.network",
    };

    const contr = new provider.Contract(
      collectionAbi,
      collection_address_testnet
    );

    const res = await contr.methods
      .mintNft({ json: json })
      .send({ from: new Address(signer_address) });
      
    console.log(res);
  };

**Comment by elasticLove1** [comment]
Hello:) This issue is from another library, not ever-sdk-js.
